### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jasonkuhrt**
Add component install instructions

### CODE REVIEW

**Comment by scottcorgan** [comment]
Is there anything else that needs to happen for it to be available on component?

**Comment by jasonkuhrt** [comment]
@scottcorgan no but anyone can do:

`component crawl scottcorgan`

**Comment by jasonkuhrt** [comment]
^ which adds it to the repository

**Comment by jasonkuhrt** [comment]
I've now done this and as you can see...

```
c search args-list                                                                                                       master 3538d61

  scottcorgan/args-list
  url: https://github.com/scottcorgan/args-list
  desc: Extract method arguments names into array.
  ★ 3
```

**Comment by scottcorgan** [comment]
Awesome, thanks so much!

**Pull request merged**
